baseURL = "https://arabianAnalyst.com"
languageCode = "en-us"
title = "المحلل العربي"
theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-78901106-1"
disqusShortname = "lmhll-l-rby"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[taxonomies]
  tag = "tags"

[permalinks]
  post = ":year/:month/:day/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "الرئيسية"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "المدونة"
    pre = "edit"
    url = "/post/"
    weight = 2
  [[menu.main]]
    name = "المواضيع"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "عني؟"
    pre = "user"
    url = "/about/"
    weight = 4


[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "مدونة متخصصة في مواضيع حول جمع وتصوير ونمذجة البيانات والتعلم الآلي"
  footerText = "صمم بواسطة [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
  hideFooter = false
  # Styling
  customCss = "/css/my_custom.css"
  highlightjsCDN = ""
  highlightingTheme = "atom-one-light"
  equationSize = 80
  profile_photo = "/images/personal_photo.jpg"
  github_source = "https://github.com/Hussain-Alsalman/Arabian_Analyst_Blog/blob/master/content/"

 [params.social]
    [[params.social.contact]]
        name = "linkedin"
        pre = "linkedin"
        link = "https://www.linkedin.com/in/hussainalsalman"
    [[params.social.contact]]
        name = "github"
        pre = "github"
        link = "https://github.com/Hussain-Alsalman"
    [[params.social.contact]]
        name = "twitter"
        pre = "twitter"
        link = "https://twitter.com/Arabian_Analyst"
    [[params.social.contact]]
        name = "email"
        pre = "mail"
        link = "mailto:ArabianAnalyst@gmail.com"
    [[params.social.contact]]
        name = "RSS"
        pre = "rss"
        link = "/index.xml"
